//@isTest(seealldata=true)
public class CreatePTSFromInventoryItemLocationTest {
    
    /*Static testMethod void TestPTSCreation(){
        
        //Lookup an inventory item location to update
        Inventory_Item_Location__c itemLocation =[SELECT Id, Count__c, re_order_Level__c, Location__c, 
                                                        re_order_quantity__c, Batch_Active__c, Inventory_Item__c 
                                                        FROM Inventory_Item_Location__c
                                                        WHERE Batch_Active__c = true AND Location__c != null 
                                                        AND Count__c != null AND re_order_quantity__c != null LIMIT 1];
        
        itemLocation.re_order_Level__c = itemLocation.Count__c;
        
        update itemLocation;
    }*/

}